backend:
  name: github
  repo: xel-a/aivertex
  branch: main

media_folder: '/src/assets/images'
public_folder: '/src/assets/images'

collections:
  - label: 'Blogs'
    name: 'blogs'
    folder: 'src/content/blogs'
    create: true
    slug: '{{slug}}'
    extension: 'md'
    format: 'frontmatter'

    fields:
      - { label: 'Title', name: 'title', widget: 'string' }

      - { label: 'Description', name: 'description', widget: 'text' }

      - { label: 'Publish Date', name: 'pubDate', widget: 'datetime' }

      - label: 'Author'
        name: 'author'
        widget: 'select'
        options:
          - Axel Ignacio

      - label: 'Category'
        name: 'category'
        widget: 'select'
        options:
          - 'Cybersecurity'
          - 'Programming'
          - 'Finance'
          - 'Design'
          - 'Testing'

      - { label: 'Tags', name: 'tags', widget: 'list' }

      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }

      - { label: 'Updated Date', name: 'updatedDate', widget: 'datetime' }

      - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: 'Labs'
    name: 'labs'
    folder: 'src/content/labs'
    create: true
    slug: '{{slug}}'
    extension: 'md'
    format: 'frontmatter'

    fields:
      - { label: 'Title', name: 'title', widget: 'string' }

      - { label: 'Description', name: 'description', widget: 'text' }

      - { label: 'Publish Date', name: 'pubDate', widget: 'datetime' }

      - label: 'Author'
        name: 'author'
        widget: 'select'
        options:
          - Axel Ignacio

      - label: 'Category'
        name: 'category'
        widget: 'select'
        options:
          - 'Cybersecurity'
          - 'Programming'
          - 'Finance'
          - 'Design'
          - 'Testing'

      - { label: 'Tags', name: 'tags', widget: 'list' }

      - label: 'Status'
        name: 'status'
        widget: 'select'
        options:
          - 'active'
          - 'paused'
          - 'completed'
        default: 'active'

      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }

      - { label: 'Updated Date', name: 'updatedDate', widget: 'datetime' }

      - { label: 'Body', name: 'body', widget: 'markdown' }

  - label: 'Project'
    name: 'projects'
    folder: 'src/content/projects'
    create: true
    slug: '{{slug}}'
    extension: 'md'
    format: 'frontmatter'

    fields:
      - { label: 'Title', name: 'title', widget: 'string' }

      - { label: 'Description', name: 'description', widget: 'text' }

      - label: 'Author'
        name: 'author'
        widget: 'select'
        options:
          - Axel Ignacio

      - label: 'Category'
        name: 'category'
        widget: 'select'
        options:
          - 'Cybersecurity'
          - 'Artificial Intelligence'
          - 'Finance'

      - { label: 'Tags', name: 'tags', widget: 'list' }

      - label: 'Links'
      - name: 'links'
      - widget: 'object'
      - fields:
          - label: 'Site'
          - name: 'site'
          - widget: 'string'

          - label: 'Repository'
          - name: 'repository'
          - widget: 'string'

      - { label: 'Draft', name: 'draft', widget: 'boolean', default: false }

      - { label: 'Updated Date', name: 'updatedDate', widget: 'datetime' }

      - { label: 'Body', name: 'body', widget: 'markdown' }
